image: "rust:latest"

stages:
  - test
  - doc
  - build

test:
  stage: test
  script:
    - apt-get install libgtk-3-dev
    - rustc --version
    - cargo --version
    - cargo test --verbose

pages:
  stage: doc
  script:
    - apt-get install libgtk-3-dev
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=tether">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
