image: "rust:latest"

stages:
  - test
  - doc
  - build

before_script:
  - apt-get update -yq
  - apt-get install -y libgtk-3-dev

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=tether">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
